services:
  - type: web
    name: wait-time-predictor-backend
    runtime: python
    plan: free
    region: oregon
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
